__author__ = 'diego'

# This is for the get_random_tag() method
predefined_tags = ["instagood", "instamood", "statigram", "iphonesia", "twelveskip", "igers", "instadaily", "tweegram",
                   "instagramhub", "follow", "bestoftheday", "igdaily", "picstitch", "followme", "instagramhub", "jj",
                   "picoftheday", "life", "instagood", "instamood", "statigram", "iphonesia", "twelveskip", "igers",
                   "instadaily", "tweegram", "instagramhub", "follow", "bestoftheday", "iphoneonly", "igdaily",
                   "picstitch", "followme", "webstagram", "jj", "picoftheday", "selfie", "me", "instagood", "instamood",
                   "iphonesia", "twelveskip", "igers", "instadaily", "tweegram", "instagramhub", "follow",
                   "bestoftheday", "iphoneonly", "igdaily", "picstitch", "beautiful", "followme", "webstagram", "jj",
                   "picoftheday", "fun", "iphonesia", "girl", "love", "boyfriend", "life", "goodtimes", "instagood",
                   "twelveskip", "igdaily", "instaphoto", "igers", "instadaily", "tweegram", "instagramhub", "follow",
                   "bestoftheday", "iphoneonly", "picstitch", "beautiful", "followme", "webstagram", "jj",
                   "picoftheday", "foodporn", "yummy", "food", "instagood", "foodie", "igdaily", "foodgasm",
                   "instaphoto", "igers", "instadaily", "tweegram", "instagramhub", "follow", "bestoftheday",
                   "followme", "webstagram", "jj", "picoftheday", "twelveskip", "picstitch", "happytummy", "tbt",
                   "throwback", "instagood", "instamood", "throwbackthursday", "old", "statigram", "iphonesia", "igers",
                   "instadaily", "tweegram", "instagramhub", "follow", "bestoftheday", "iphoneonly", "igdaily",
                   "picstitch", "followme", "webstagram", "jj", "picoftheday", "goodtimes", "fitness", "fit", "healthy",
                   "eatclean", "hardwork", "gym", "fitspiration", "dedicated", "motivation", "inspiration", "instagood",
                   "instamood", "statigram", "iphonesia ", "igers", "instadaily", "tweegram", "instagramhub",
                   "twelveskip", "follow", "bestoftheday", "iphoneonly", "igdaily", "picstitch", "followme",
                   "webstagram", "jj", "picoftheday", "tgif", "friday", "fridaynight", "yolo", "instagood", "instamood",
                   "twelveskip", "statigram", "iphonesia ", "igers", "instadaily", "tweegram", "instagramhub", "follow",
                   "bestoftheday", "iphoneonly", "igdaily", "picstitch", "followme", "webstagram", "jj", "picoftheday",
                   "all_shots", "party", "yolo", "livelife", "fun", "happy", "instagood", "twelveskip", "instamood",
                   "statigram", "iphonesia ", "igers", "instadaily", "tweegram", "instagramhub", "follow",
                   "bestoftheday", "iphoneonly", "igdaily", "picstitch", "followme", "webstagram", "jj", "picoftheday",
                   "all_shots", "ootd", "style", "fashion", "instagood", "instamood", "twelveskip", "statigram",
                   "iphonesia ", "instafashion", "outfit", "igers", "instadaily", "tweegram", "instagramhub", "follow",
                   "bestoftheday", "iphoneonly", "igdaily", "potd", "followme", "webstagram", "jj", "picoftheday",
                   "all_shots", "TagsForLikes", "bff", "bestfriends", "besties", "love", "cute", "partners",
                   "twelveskip", "statigram", "jj", "a", "instadaily", "instagood", "follow", "lb", "bestoftheday",
                   "igdaily", "all_shots", "tweegram", "picoftheday", "igers", "friends", "nice", "christmas", "love",
                   "instalove", "xmas", "winter", "twelveskip", "happyseason", "tree", "family", "snow", "white",
                   "candy", "baby", "present", "gifts", "holiday", "lights", "decoration", "gift", "season",
                   "mostwonderfultimeoftheyear", "Likesforlikes", "Turtlelove", "Turtlelover", "L4l", "Likesreturned",
                   "Turtles_of_Instagram", "Likes4likes", "Turtlelife", "Followforfollow", "F4f", "Mypet", "Likeforlikes",
                   "TopLikeTags", "Pet", "Singing", "Guitarcover", "L4l", "Guitarvideo", "Instacover", "Music",
                   "Likesreturned", "Coversong", "Likes4likes", "Likesforlikes", "Acousticguitar", "Followforfollow",
                   "Acousticcover", "F4f", "Electricguitar", "Guitarplayer", "Topliketags", "Guitarra", "Guitarporn",
                   "Guitarhero", "Likesback", "Guitarsolo", "Fingerstyle", "Chords", "Youtuber", "Strum", "Rnb",
                   "Music", "Likesreturned", "Instamusic", "Rappers", "Likesforlikes", "Newmusic", "Newsong",
                   "Likes4likes", "Newartist", "Drdre", "Ymcmb", "Jayz", "F4f", "Goodmusic", "50cent",
                   "Followforfollow", "Emcee", "Originalsong", "Likesback", "Instavideo", "Bars", "Recording",
                   "Blackandwhiteonly", "Likesreturned", "Bnw", "Bnw_life", "Likeforlike", "Bnw_captures", "L4l",
                   "Blackwhite", "Blackwhitephoto", "Likesforlikes", "Vsco", "Vscool", "L4l", "Vscocam", "TopLikeTags",
                   "Photooftheday", "Bw_crew", "Picoftheday", "Photograph", "Bnw_society", "Photographier", "Vscolife",
                   "Blacknwhite", "Blacknwhite_perfection", "Instablack_and_White", "bw", "Insta_bw", "shoutout",
                   "shoutouts", "shout", "out @topliketags", "shoutouter", "clubshoutout", "topliketags", "s4s",
                   "instagood", "shout_out", "love", "so", "shoutout4shoutout", "sobackteam", "soback", "follow",
                   "instashoutout", "instaso", "shoutoutforshoutout", "shoutoutback", "shoutmeout",
                   "followshoutoutlikecomment", "shouts", "shoutoutpage", "shoutoutteam", "shoutoutmes", "Topliketags",
                   "Guys", "Girls", "LikesforLike", "Musicians", "Dance", "L4l", "Bored", "Partyline",
                   "Followforfollow", "Sleepingsquad", "Likeforlike", "5Squad", "Likesreturned", "ask_questions",
                   "Random", "Singing", "Lgbt", "Alternative", "Funny", "Love", "Younowfamily", "Hot", "Youtuber"]