__author__ = 'diego'

# This is for the get_random_tag() method
# Will be deleted if chosen
predefined_unique_tags = ["bodyBuilding", "legday", "cardio", "shredded", "fitness", "body", "InstaGood", "happy"
                          "gym", "healthy", "dog", "puppy", "pup", "hashgram", "eyes", "pet", "pets", "animal",
                          "animals", "petstagram", "petsagram", "dogsitting", "banoosh", "dogs_ofInstagram",
                          "iLove_my_dog", "instagramdogs", "dogstagram", "dogoftheday", "loveDogs", "love_Puppies",
                          "hound", "aDoRaBle", "doglover", "instapuppy", "instadog", "rabbit", "hutch", "floppy",
                          "ears", "fur", "workout", "myfit", "fitnessmotivation", "workhard", "training", "TFLers",
                          "fit", "motivation", "eatclean", "gains", "train", "instafit", "motivated", "beast",
                          "beastmode", "love", "followme", "jackrussell", "terrier", "jackrussellterrier",
                          "jackrussellinstagram", "jrt", "parson", "parsonRussell", "PaRsOnPoWeR",
                          "pArsonrUssellterrier", "parsonrussellofinstagram", "boomer", "mydog", "jrtpost",
                          "jrtthailand", "sleepydog", "instajrt", "jacksapeca", "caosapeca", "jackterrorista",
                          "darainbowfollowers", "buttons", "colours", "retrica", "picollage", "moldiv", "graffifi",
                          "befree", "quotes", "neon", "robot", "protein", "proteins", "lowcarb", "biologisch",
                          "eatcleandielean", "fightforfit", "femalemotivation", "lovingfitness", "savino", "pectoral",
                          "bigarm", "lord", "rings", "eatthemveggies", "realfoodporn", "vitaminbomb", "colorfulfood",
                          "chefsabs", "inthakitchen", "cheeseomelette", "foodpower", "workoutmeal", "breaktfast",
                          "poledancer", "almond", "bisquits", "gnam", "healtly", "comidasana", "comesano",
                          "healthymeal", "saludable", "vidasana", "comelimpio", "mission", "possible", "mybodymission",
                          "greanfood", "eatnatural", "healthychoices", "getfit", "avocado", "salad", "cucumber",
                          "hkfoodie", "hkfood", "korea", "korean", "koreanfood", "pomegranate", "juice", "time",
                          "goulash", "gulas", "bread", "mustbe", "myfavorite", "cooking", "gastro", "delicous",
                          "foodstamping", "mmm", "kuliner", "absolutely", "no", "wholemeal", "hemp", "work", "oslo",
                          "norge", "rawfood", "veganofig", "cleanse", "juicecleanse", "food", "foodporn", "instafood",
                          "TagsForLikes", "photooftheday", "dinner", "lunch", "breakfast", "fresh", "tasty", "foodpic",
                          "hungry", "foodgasm", "healthylife", "cleanfood", "healthyfood", "weightloss",
                          "sabatoitaliano", "pranzo", "peperoniripieni", "hot", "burger", "fakeshack", "foodtrip",
                          "classy", "tommyhilfiger", "watch", "familydinner", "skoda", "rs", "finnishman", "finnishboy",
                          "ontheroadgain", "fineanddine", "asiatique", "riverfront", "chillax", "steak", "grilled",
                          "grilling", "cook", "instadinner", "foodphot", "dye", "dyedfood", "rainbow", "dessert",
                          "desserts", "yum", "yummy", "amazing", "sweet", "chocolate", "cake", "icecream",
                          "dessertporn", "delish", "foods", "delicious", "eat", "eating", "foodpics", "sweettooth",
                          "latergram", "ganache", "cioccolato", "macarons", "paris", "lyon", "marseille", "zaynmalik",
                          "liampayne", "niam", "onedirection", "1direction", "1d", "larrysmut", "larrysex", "larryporn",
                          "larryfluff", "larryisreal", "5secondsofsummer", "luke", "lucas", "hemmo", "hemmo1996",
                          "hemmings", "mrshemmings", "cal", "calum", "hood", "mrshood", "mukeaf", "lashton", "mashton",
                          "cashton", "otp", "ash", "ashton", "irwin", "ilikeitaly", "browsingitaly", "vscoitaly",
                          "instagrammers", "instalove", "comment", "shoutout", "iphoneography", "androidography",
                          "filter", "filters", "hipster", "contests", "pics", "instafamous", "popularpic",
                          "popularphoto", "instapicmixapp", "pink", "throwbackthursday", "music", "art", "f4f",
                          "repost", "blue", "makeup", "boyfriend", "statigram", "votetrismtv", "votethomasmtv",
                          "exo", "callmebaby", "bestofbestph2015", "celebrityawards2015", "rt", "gameinsight", "mufc",
                          "mufclive", "mgwv", "porn", "followtrick", "risingstar", "teamfollowback", "nsfw", "adult",
                          "ericharris", "nowplaying", "ggmu", "happysehunday", "songkranfestival", "ipadgames",
                          "retweet", "ipad", "followback", "sougofollow", "revealmariah", "news", "otw6days",
                          "msgmyinspiration", "ff", "cfc", "manchesterderby", "quran", "parisroubaix", "mcfc",
                          "android", "initalkshowadafatin", "jugarapensar", "stereoneteps4", "iremlysmdemi",
                          "yfsficons", "peopleskills", "undianfreshcool", "dgs", "spinnrkpop", "spiritchat",
                          "takibetakip", "mutv", "kmjs10", "50sombrasdegrey", "petitmiradio", "tothemoonandback",
                          "enzozelocchi", "awards", "bayfm", "2ndchance", "films", "a1apparel", "frankedwardsdonmoen",
                          "jiterrorists", "aibou", "marriageinislam", "bestactor", "sb69a", "qubintang", "sm26015160",
                          "yoona", "m88quiz", "kaji1134", "favorite", "kokaku_a", "producer", "dalailama", "lovelive",
                          "na246belongstomqm", "fbjokes", "catchdrogon", "favcounter", "sundaycandy", "bs11",
                          "bestravelgirls", "mufcidlive", "tmltalk", "belieber", "megotanwa_before30", "leafs",
                          "aceitadilmavez", "pptvhd", "saludduran", "votalali", "mtvclash", "noisundays", "gain",
                          "christinagrimmie", "cuposhweek", "kenyenpj2015", "teamamosxriz", "goooaaalll",
                          "votadulcemaria", "spanish", "gente", "cashflow", "revistas", "przeplywy", "directo",
                          "thelover", "diskidivas", "ikleadsrestfollow", "abrahammateoen15a20", "talkradio",
                          "thesocialexperiment", "etotama", "valilik", "laught", "vinecanario", "konser", "me",
                          "follow", "tbt", "cute", "like", "tagsforlikes", "beautiful", "girl", "picoftheday",
                          "instadaily", "fun", "smile", "selfie", "igers", "like4like", "friends", "summer", "fashion",
                          "instalike", "swag", "tflrs", "bestoftheday", "instamood", "follow4follow", "style", "lol",
                          "like_for_like", "l4l", "pretty", "nofilter", "wcw", "family", "webStagram", "my",
                          "iPhoneOnly", "life", "tweegram", "hair", "all_shots", "instago", "sun", "bored", "instacool"]

# Won't be deleted even if chosen
predefined_non_unique_tags = ("bodyBuilding", "legday", "cardio", "shredded", "fitness", "body", "InstaGood", "happy"
                          "gym", "healthy", "dog", "puppy", "pup", "hashgram", "eyes", "pet", "pets", "animal",
                          "animals", "petstagram", "petsagram", "dogsitting", "banoosh", "dogs_ofInstagram",
                          "iLove_my_dog", "instagramdogs", "dogstagram", "dogoftheday", "loveDogs", "love_Puppies",
                          "hound", "aDoRaBle", "doglover", "instapuppy", "instadog", "rabbit", "hutch", "floppy",
                          "ears", "fur", "workout", "myfit", "fitnessmotivation", "workhard", "training", "TFLers",
                          "fit", "motivation", "eatclean", "gains", "train", "instafit", "motivated", "beast",
                          "beastmode", "love", "followme", "jackrussell", "terrier", "jackrussellterrier",
                          "jackrussellinstagram", "jrt", "parson", "parsonRussell", "PaRsOnPoWeR",
                          "pArsonrUssellterrier", "parsonrussellofinstagram", "boomer", "mydog", "jrtpost",
                          "jrtthailand", "sleepydog", "instajrt", "jacksapeca", "caosapeca", "jackterrorista",
                          "darainbowfollowers", "buttons", "colours", "retrica", "picollage", "moldiv", "graffifi",
                          "befree", "quotes", "neon", "robot", "protein", "proteins", "lowcarb", "biologisch",
                          "eatcleandielean", "fightforfit", "femalemotivation", "lovingfitness", "savino", "pectoral",
                          "bigarm", "lord", "rings", "eatthemveggies", "realfoodporn", "vitaminbomb", "colorfulfood",
                          "chefsabs", "inthakitchen", "cheeseomelette", "foodpower", "workoutmeal", "breaktfast",
                          "poledancer", "almond", "bisquits", "gnam", "healtly", "comidasana", "comesano",
                          "healthymeal", "saludable", "vidasana", "comelimpio", "mission", "possible", "mybodymission",
                          "greanfood", "eatnatural", "healthychoices", "getfit", "avocado", "salad", "cucumber",
                          "hkfoodie", "hkfood", "korea", "korean", "koreanfood", "pomegranate", "juice", "time",
                          "goulash", "gulas", "bread", "mustbe", "myfavorite", "cooking", "gastro", "delicous",
                          "foodstamping", "mmm", "kuliner", "absolutely", "no", "wholemeal", "hemp", "work", "oslo",
                          "norge", "rawfood", "veganofig", "cleanse", "juicecleanse", "food", "foodporn", "instafood",
                          "TagsForLikes", "photooftheday", "dinner", "lunch", "breakfast", "fresh", "tasty", "foodpic",
                          "hungry", "foodgasm", "healthylife", "cleanfood", "healthyfood", "weightloss",
                          "sabatoitaliano", "pranzo", "peperoniripieni", "hot", "burger", "fakeshack", "foodtrip",
                          "classy", "tommyhilfiger", "watch", "familydinner", "skoda", "rs", "finnishman", "finnishboy",
                          "ontheroadgain", "fineanddine", "asiatique", "riverfront", "chillax", "steak", "grilled",
                          "grilling", "cook", "instadinner", "foodphot", "dye", "dyedfood", "rainbow", "dessert",
                          "desserts", "yum", "yummy", "amazing", "sweet", "chocolate", "cake", "icecream",
                          "dessertporn", "delish", "foods", "delicious", "eat", "eating", "foodpics", "sweettooth",
                          "latergram", "ganache", "cioccolato", "macarons", "paris", "lyon", "marseille", "zaynmalik",
                          "liampayne", "niam", "onedirection", "1direction", "1d", "larrysmut", "larrysex", "larryporn",
                          "larryfluff", "larryisreal", "5secondsofsummer", "luke", "lucas", "hemmo", "hemmo1996",
                          "hemmings", "mrshemmings", "cal", "calum", "hood", "mrshood", "mukeaf", "lashton", "mashton",
                          "cashton", "otp", "ash", "ashton", "irwin", "ilikeitaly", "browsingitaly", "vscoitaly",
                          "instagrammers", "instalove", "comment", "shoutout", "iphoneography", "androidography",
                          "filter", "filters", "hipster", "contests", "pics", "instafamous", "popularpic",
                          "popularphoto", "instapicmixapp", "pink", "throwbackthursday", "music", "art", "f4f",
                          "repost", "blue", "makeup", "boyfriend", "statigram", "votetrismtv", "votethomasmtv",
                          "exo", "callmebaby", "bestofbestph2015", "celebrityawards2015", "rt", "gameinsight", "mufc",
                          "mufclive", "mgwv", "porn", "followtrick", "risingstar", "teamfollowback", "nsfw", "adult",
                          "ericharris", "nowplaying", "ggmu", "happysehunday", "songkranfestival", "ipadgames",
                          "retweet", "ipad", "followback", "sougofollow", "revealmariah", "news", "otw6days",
                          "msgmyinspiration", "ff", "cfc", "manchesterderby", "quran", "parisroubaix", "mcfc",
                          "android", "initalkshowadafatin", "jugarapensar", "stereoneteps4", "iremlysmdemi",
                          "yfsficons", "peopleskills", "undianfreshcool", "dgs", "spinnrkpop", "spiritchat",
                          "takibetakip", "mutv", "kmjs10", "50sombrasdegrey", "petitmiradio", "tothemoonandback",
                          "enzozelocchi", "awards", "bayfm", "2ndchance", "films", "a1apparel", "frankedwardsdonmoen",
                          "jiterrorists", "aibou", "marriageinislam", "bestactor", "sb69a", "qubintang", "sm26015160",
                          "yoona", "m88quiz", "kaji1134", "favorite", "kokaku_a", "producer", "dalailama", "lovelive",
                          "na246belongstomqm", "fbjokes", "catchdrogon", "favcounter", "sundaycandy", "bs11",
                          "bestravelgirls", "mufcidlive", "tmltalk", "belieber", "megotanwa_before30", "leafs",
                          "aceitadilmavez", "pptvhd", "saludduran", "votalali", "mtvclash", "noisundays", "gain",
                          "christinagrimmie", "cuposhweek", "kenyenpj2015", "teamamosxriz", "goooaaalll",
                          "votadulcemaria", "spanish", "gente", "cashflow", "revistas", "przeplywy", "directo",
                          "thelover", "diskidivas", "ikleadsrestfollow", "abrahammateoen15a20", "talkradio",
                          "thesocialexperiment", "etotama", "valilik", "laught", "vinecanario", "konser", "me",
                          "follow", "tbt", "cute", "like", "tagsforlikes", "beautiful", "girl", "picoftheday",
                          "instadaily", "fun", "smile", "selfie", "igers", "like4like", "friends", "summer", "fashion",
                          "instalike", "swag", "tflrs", "bestoftheday", "instamood", "follow4follow", "style", "lol",
                          "like_for_like", "l4l", "pretty", "nofilter", "wcw", "family", "webStagram", "my",
                          "iPhoneOnly", "life", "tweegram", "hair", "all_shots", "instago", "sun", "bored", "instacool")